include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - cancel_subscriptions
    - close_sinks
    - prefer_const_constructors
    - prefer_final_in_for_each
    - prefer_single_quotes
analyzer:
  errors:
    todo: warning
    missing_return: error
    dead_code: error
    invalid_annotation_target: ignore
    prefer_single_quotes: warning
  exclude:
    - "**/*.barrel.dart"
    - "**/*.drift.dart"
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
